spring.application.name=ictmanager

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ICTManager
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Fixtures Path
#server.path=D:\\Maintenance\\

# Enable caching
spring.cache.type=simple

# Authentication
network.share.username=ict_her
network.share.password=Tastatura135!
maintenance.subfolder=seica/Maintenance
executor.thread-pool-size=10